### PR TITLE
feat(ruby): Added Neotest integration for ruby

### PR DESCRIPTION
**Pull request by dsisnero**
Added neotest integration for ruby - not sure if should add it here and not sure if this breaks neotest for other languages or if this is the best way to do this.  Should I add to test/neotest instead?

### CODE REVIEW

**Comment by Uzaaft** [comment]
Please add a note in the readme of this pack about the test integration.

**Comment by dsisnero** [comment]
When I try :Neotest run - I get No tests found - can someone fix or explain how I need to fix this to get it to find the tests for ruby

**Review by Uzaaft — DISMISSED** [review]

**Comment by Uzaaft** [comment]
> When I try :Neotest run - I get No tests found - can someone fix or explain how I need to fix this to get it to find the tests for ruby

I'm going to mark this PR as a draft until you've solved this.

**Comment by Uzaaft** [comment]
@dsisnero Closing this PR for now due to inactivity. Please open a new one whenever you've ready and the branch works.

**Pull request closed without merging**
