### PR TITLE
fix(typescript): lazy load tsc on cmd

### PR DESCRIPTION
**Pull request by Subjective**

### CODE REVIEW

**Comment by owittek** [comment]
Hey! Could you please explain why we should load on the command instead of filetype?

**Comment by Subjective** [comment]
From what I can tell, the only time you use TSC is when running the command for it. I don't think it's necessary to load it every time. But supposing we were to load it on filetype, then I think it would make sense to add typescriptreact, javascript, and javascriptreact filetypes.

**Comment by Subjective** [comment]
Previously, TSC was also being loaded upon opening any filetype (from the AstroFile event), which is not ideal.

**Comment by owittek** [comment]
Makes sense!

**Review by owittek — APPROVED** [review]

**Pull request merged**
