### PR TITLE
fix(editing-support): wrap all require calls to refactoring in function

### PR DESCRIPTION
**Pull request by jay-babu**
Before this, I got a module not found error. Wrapping it in a function, the require call is deferred until the keypress is run where the module is now available

### CODE REVIEW

**Comment by Uzaaft** [comment]
@jay-babu  I was debugging this myself. Thanks for catching it! And happy new year

**Comment by Uzaaft** [comment]
Fixed one small issue @jay-babu Where the issue still appears when running `nvim`. This should work on all edge cases now.

**Review by Uzaaft — APPROVED** [review]

**Comment by mehalter** [comment]
Just for future reference, this should be `fix(refactoring-nvim): ...`

**Comment by Uzaaft** [comment]
@mehalter That one slipped trough by me. I thought I had changed the PR title. My bad!

**Pull request merged**
