### PR TITLE
fix(nix): Fix wrong lsp in nix pack.

### PR DESCRIPTION
**Pull request by Uzaaft**

### CODE REVIEW

**Comment by Uzaaft** [comment]
R? @AstroNvim/astrocommunity-maintainers

**Comment by luxus** [comment]
i changed it locally to https://github.com/nix-community/nixd
and alejandra to nixfmt (waiting for https://github.com/NixOS/nixfmt/issues/153)
but just days ago..

**Comment by Uzaaft** [comment]
> i changed it locally to https://github.com/nix-community/nixd (via https://github.com/nix-community/nixd/blob/main/nixd/docs/editor-setup.md) and alejandra to nixfmt with conform (waiting for [NixOS/nixfmt#153](https://github.com/NixOS/nixfmt/issues/153)) but just days ago.. but both are bleeding edge right now. i wanted to wait until nixOS 2405 is released and some more testing
> 
> ```lua
> return {
>   {
>     "nvim-treesitter/nvim-treesitter",
>     optional = true,
>     opts = function(_, opts)
>       if opts.ensure_installed ~= "all" then
>         opts.ensure_installed = require("astrocore").list_insert_unique(opts.ensure_installed, { "nix" })
>       end
>     end,
>   },
>   {
>     "AstroNvim/astrolsp",
>     -- we must use the function override because table merging
>     -- does not play nicely with list-like tables
>     ---@param opts AstroLSPOpts
>     opts = function(plugin, opts)
>       -- safely extend the servers list
>       opts.servers = opts.servers or {}
>       vim.list_extend(opts.servers, {
>         "nixd",
>         -- add more servers as needed...
>       })
>     end,
>   },
>   {
>     "nvimtools/none-ls.nvim",
>     optional = true,
>     opts = function(_, opts)
>       local nls = require "null-ls"
>       if type(opts.sources) == "table" then
>         vim.list_extend(opts.sources, {
>           nls.builtins.code_actions.statix,
>           nls.builtins.formatting.alejandra,
>           nls.builtins.diagnostics.deadnix,
>         })
>       end
>     end,
>   },
>   {
>     "stevearc/conform.nvim",
>     optional = true,
>     opts = {
>       formatters_by_ft = {
>         nix = { "nixfmt" },
>       },
>     },
>   },
>   -- {
>   --   "mfussenegger/nvim-lint",
>   --   optional = true,
>   --   opts = {
>   --     linters_by_ft = {
>   --       nix = { "statix", "nix" },
>   --     },
>   --   },
>   -- },
> }
> ```
> 
> and i guess it makes sense to add deadnix https://github.com/bondzula/nvim/blob/7a58fd58857a9a121df9703d4ad132b9bb583e56/lua/plugins/nvim-lint.lua#L9-L41

That’s outside of the scope of this PR.

**Comment by luxus** [comment]
still not sure if it makes sense to merge this and then switch to the official lsp when it is in stable next month

**Comment by Uzaaft** [comment]
> still not sure if it makes sense to merge this and then switch to the official lsp when it is in stable next month but yes the nil_ls change was in my pr that got lost :D

It’s still a month away.

**Review by luxus — APPROVED** [review]
lgtm

**Pull request merged**
