### PR TITLE
feat(typescript): Swap out eslint_d with eslint-lsp

### LINKED ISSUE #593: eslint-lsp over eslint_d in the typescript pack
### Is your feature related to a problem?

When using eslint_d via null-ls it means you cannot configure eslint like the lsp so you are limited on how you use it.

### Describe the new feature

- Remove eslint_d
- Add eslint-lsp (alongside tsserver)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Uzaaft**
Closes #593 .
Partiallly solves #590 
To change and use this branch, add:

```lua
{
 "AstroNvim/astrocommunity",
branch = "eslint-lsp",
...
}
```

### CODE REVIEW

**Comment by Infonautica** [comment]
From the brief testing everything works good and as expected 👌 
But i'll try it out more during the week

**Comment by Infonautica** [comment]
Please update Readme file for the pack as well:
https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/typescript/README.md

**Comment by Uzaaft** [comment]
> Please update Readme file for the pack as well: [`main`/lua/astrocommunity/pack/typescript/README.md](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/typescript/README.md?rgh-link-date=2023-10-08T19%3A30%3A07Z)

Will do it, if we decide to go forward with eslint-lsp :)

**Comment by Uzaaft** [comment]
@mehalter  I see that the dap file is named as deno. Can I include a path for that here, or should that be a seperate PR? 
image

**Comment by Infonautica** [comment]
@Uzaaft I've been using this branch for 3 days straight and have not encountered any issues so far 👍

**Comment by mehalter** [comment]
> @mehalter I see that the dap file is named as deno. Can I include a path for that here, or should that be a seperate PR?

I think you can do that here no problem @Uzaaft !

**Review by mehalter — APPROVED** [review]
LGTM!

**Comment by tofulm** [comment]
since the update, I get this error : `[lspconfig] Unable to find ESLint library.`

**Comment by Uzaaft** [comment]
Make sure eslint is in the project

**Comment by tofulm** [comment]
eslint is installed globally. I had to install it in my project, and it's ok
Is it possible to configure to use eslint global

**Pull request merged**
