### PR TITLE
feat(pack): add ron tree-sitter for rust develop.

### PR DESCRIPTION
**Pull request by chaozwn**

### CODE REVIEW

**Comment by Uzaaft** [comment]
Could you provide some context as to why this should be in the rust pack?

**Comment by Uzaaft** [comment]
Ping @chaozwn

**Comment by chaozwn** [comment]
> Ping @chaozwn

This is actually a commonly used Rust library, and I believe our package should offer an experience as close to that of an IDE as possible. We should provide syntax highlighting for some of the common patterns.

**Comment by Uzaaft** [comment]
Ron is a file format, it should be it's own pack imo.

**Comment by Uzaaft** [comment]
Going ahead and closing this. Please add it as a separate pack.

**Pull request closed without merging**
