### PR TITLE
fix(coc-nvim): fix heirline with coc list

### PR DESCRIPTION
**Pull request by wroyca**
## 📑 Description

Fix a very annoying issue where CoC would overwrite heirline. Note that we do lose the count information, so we'll have to integrate it into heirline, probably by looking at how it is done internally

### Before:
image

### After:
image

### CODE REVIEW

**Comment by Uzaaft** [comment]
@wroyca  I'll take a look at coc.nvim tomorrow to see if we can reproduce whatever they do, if not I'll merge this in.

Can you resolve the conflicts while you wait?

**Comment by Uzaaft** [comment]
Didn't manage to find out how they do things. 
I think we can add a note about the behavior in the readme, and call it a day.
cc @mehalter

**Review by mehalter — CHANGES_REQUESTED** [review]
there are a lot of issues here:

1. this is super non-performant because setting `vim.opts` for some reason is super expensive imo
2. This is pulling the `laststatus` from the `opts` which is not necessarily true if the user has changed it at runtime. This should be saved to a temporary variable the old value.

These can both be fixed by (1) saving a temp variable with the current `laststatus`, check if they are equal and only do the assignment if they are different. It shouldn't reference `options.options.opt.laststatus` at all.

Ideally this is just not our problem and should be reported upstream haha

**Comment by wroyca** [comment]
> there are a lot of issues here:
> 
>     1. this is super non-performant because setting `vim.opts` for some reason is super expensive imo
> 
>     2. This is pulling the `laststatus` from the `opts` which is not necessarily true if the user has changed it at runtime. This should be saved to a temporary variable the old value.
> 
> 
> These can both be fixed by (1) saving a temp variable with the current `laststatus`, check if they are equal and only do the assignment if they are different. It shouldn't reference `options.options.opt.laststatus` at all.
> 
> Ideally this is just not our problem and should be reported upstream haha

It's a trade-off for sure. I don't mind closing this for now, and then we may see with upstream how to approach it later

**Pull request closed without merging**
