### PR TITLE
chore: replace config function with opts table where possible

### PR DESCRIPTION
**Pull request by Subjective**

### CODE REVIEW

**Review by owittek — APPROVED** [review]
LGTM

**Comment by owittek** [comment]
@mehalter the pipeline seems to not like `chore`.

**Comment by mehalter** [comment]
We require scope for PRs, I can merge this

**Comment by mehalter** [comment]
@owittek good to require scope which basically requires PRs do one thing at a time. For big stuff like this it's alright to wait for an admin to approve it hehe

**Pull request merged**
