### PR TITLE
feat(lsp): add inc-rename

### PR DESCRIPTION
**Pull request by 0xricksanchez**
Added this one a while back and saw that its mentioned in #66. 
Not using this plugin much anymore as all my LSPs support renaming nowadays.

### CODE REVIEW

**Comment by luxus** [comment]
didn't know that this is covered by lsp by now
maybe this is not necessary at all?
does it rename the stuff live?

**Comment by 0xricksanchez** [comment]
For example, this is what rust_analyzer seems to offer me via `<leader>lr` (Rename current symbol).

image

This doesn't seem to work for cases where the attached LS doesn't offer this, so if I e.g. have a `.json` file with all these attached: `jsonls`, `jsonlint`, `jq` ... I don't get the option. 
So, This may still be a nice complementary plugin to have for some cases/languages… And yes, it offers a "live-preview" as in it highlights all occurrences and updates them live when you change the symbol name.

If we wanna add this, maybe changing this to `<leader>lR` might be a good default fit then

**Comment by Uzaaft** [comment]
IncRename works hand in hand with the LSP guys.

**Comment by Uzaaft** [comment]
So imho, if  you're using IncRename, you WANT it to override the <leader>lr binding.

**Comment by 0xricksanchez** [comment]
Then I guess the PR does exactly what we want?

**Comment by Uzaaft** [comment]
Yes, LGTM 🚀

**Review by Uzaaft — APPROVED** [review]

**Review by luxus — APPROVED** [review]

**Review by luxus — CHANGES_REQUESTED** [review]
can u please change the folder to lsp
see http://neovimcraft.com/plugin/smjonas/inc-rename.nvim/index.html

**Review by luxus — APPROVED** [review]

**Pull request merged**
