### PR TITLE
feat(debugging): Add nvim-chainsaw

### LINKED ISSUE #729: Adding https://github.com/chrisgrieser/nvim-chainsaw
### Is your feature related to a problem?

No

### Describe the new feature

I'll probably add this via PR, but in case anyone gets to it before me: https://github.com/chrisgrieser/nvim-chainsaw

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Uzaaft**
Closes #729

### CODE REVIEW

**Comment by luxus** [comment]
no mappings?

**Comment by luxus** [comment]
maybe @jay-babu some ideas for mappings?

**Comment by Uzaaft** [comment]
He can add them later on @luxus

**Comment by mehalter** [comment]
This should load on file opening I believe. Or if someone wants to maintain the filetypes that it has built in support for. It automatically creates logs right?

**Comment by Uzaaft** [comment]
@mehalter Wanna leave a review?🥹

**Pull request merged**
