### PR TITLE
Added Keymapping for go pack

### PR DESCRIPTION
**Pull request by Rishikesh01**
Imo these keymapping should atleast be provided in community repo, as debugging and running tests is quite common

### CODE REVIEW

**Comment by Uzaaft** [comment]
Your PR doesnt make sense.

**Comment by Uzaaft** [comment]
The keys you added should be in the nvim-dap-go spec, not where you placed them.

**Comment by Rishikesh01** [comment]
@Uzaaft The aim of this PR is improve user experience as

Running `Pack` commands like `:GoTestFunc` ruin's user experience IMO.

For example:

In VS code if I want to run a single test I would Simply click on the inlay button `run test`.
VScode is a GUI application sense to provides a `run test` feature via point and click method as a User would expect.


The point I am trying to make here is, Astronvim is a config that greatly simplifies using nvim TUI, it should have keymapping for common operations like running tests, debugging test, adding tags, filling structs etc... in it's community plugin.

**Comment by Uzaaft** [comment]
I’m not disputing the value of those commands. But your code wouldnt work.

**Pull request closed without merging**
