### PR TITLE
fix(catppuccin): added name for catppuccin integrations

### LINKED ISSUE #902: Lazy warning for noice.nvim
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux

### Terminal/GUI

kitty

### Describe the bug

Including noice.nvim results in an error message from lazy.nvim:
Lua module not fonud for config of nvim. Please use a `config()` function instead.
This seems to be because of a missing name line in the catppuccin integration config
```lua
  {
    "catppuccin/nvim",
    name = "catpuccin", -- << THIS LINE IS MISSING
    optional = true,
    ---@type CatppuccinOptions
    opts = { integrations = { noice = true } },
  },
``` 
Other community plugins with catppuccin integrations might have this issue as well

### Steps to Reproduce

```lua
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.utility.noice-nvim" },
  -- import/override with your plugins folder
}
```

### Expected behavior

No error message

### Screenshots

image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tobias-haenel**
## 📑 Description

Adding the name field to catppuccin integration plugin specs. To ensure that lazy uses the correct config function. See #902 for details

### CODE REVIEW

**Comment by luxus** [comment]
i added the solution to the issue

**Comment by Uzaaft** [comment]
@tobias-haenel  The idea is good.
We should instead do this:
`{ import = "astrocommunity.colorscheme.catppuccin", optional = true, opts = {...} },`

**Comment by luxus** [comment]
@Uzaaft this makes no sense, why should be the name here..
please read https://github.com/AstroNvim/astrocommunity/issues/902

**Comment by Uzaaft** [comment]
ah, mb

**Pull request closed without merging**
