### PR TITLE
feat(pack): add tailwindcss pack

### PR DESCRIPTION
**Pull request by taskylizard**
I really hope the ci doesn't scream at me again.

### CODE REVIEW

**Review by A-Lamia — APPROVED** [review]
LGTM!

**Comment by A-Lamia** [comment]
Thank you for your contribution!

**Comment by luxus** [comment]
does 
```lua
  {
    "NvChad/nvim-colorizer.lua",
    opts = {
      user_default_options = {
        tailwind = true,
      },
    },
  },
  ```
  make sense?

**Comment by taskylizard** [comment]
I had ccc.nvim enabled instead of nvim-colorizer so I didn't know actually, will fix.

**Pull request merged**
