### PR TITLE
fix(go): install missing `goimports`

### PR DESCRIPTION
**Pull request by mehalter**
## 📑 Description

This supersedes #1162. `gopls` uses `gofumpt` for formatting so we can leverage that after running `goimports`

### CODE REVIEW

**Review by Uzaaft — APPROVED** [review]

**Comment by Uzaaft** [comment]
Fixes mistake done in #1059 I think?

**Comment by mehalter** [comment]
Yup!

**Comment by pgr0ss** [comment]
Don't you still need to install `gofumpt` via `mason-tool-installer`? In my local testing, it didn't run `gofumpt` until I added this:
```lua
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = function(_, opts)
      opts.ensure_installed = require("astrocore").list_insert_unique(opts.ensure_installed, { "gofumpt" })
    end,
  },
```

**Comment by mehalter** [comment]
It doesn't need to, it uses `gopls` for formatting since that has `gofumpt` built in

**Comment by mehalter** [comment]
I can take a look in a bit, but `gopls` _should_ be formatting after `goimports` 😅

**Comment by mehalter** [comment]
Just tested @pgr0ss and it works great! no `gofumpt` necessary :D `gopls` handles the formatting itself

**Comment by pgr0ss** [comment]
@mehalter Do we need to add `gofumpt = true` to the `gopls` config, then? This says the default is `false`:

https://github.com/golang/tools/blob/master/gopls/doc/settings.md#gofumpt-bool

When I added `gofumpt = true` here it started working for me:

https://github.com/AstroNvim/astrocommunity/blob/76f4f81b5da0f1573a2d7040d7909e11f1239fac/lua/astrocommunity/pack/go/init.lua#L11-L51

**Comment by mehalter** [comment]
oh yeah maybe! I see, without it it's just running `go fmt`. Yup that would be a great addition. One second and I'll add it

**Pull request merged**
