### PR TITLE
fix(yanky-nvim): Fix yanky.nvim loading when restoring session

### PR DESCRIPTION
**Pull request by chaozwn**
there can not set event 'User AstroFile', because restore session from resession.nvim will not tigger 'User AstroFile' event.

### CODE REVIEW

**Comment by Uzaaft** [comment]
Updated the title.
@chaozwn  I don't really understand the initial "bug". Was the issue caused by "User AstroFile"?

**Comment by chaozwn** [comment]
> Updated the title. @chaozwn I don't really understand the initial "bug". Was the issue caused by "User AstroFile"?



> Updated the title. @chaozwn I don't really understand the initial "bug". Was the issue caused by "User AstroFile"?

This plugin overwrites our y key, but many times it starts up as not loaded, causing the y key to be unusable. Therefore, we need to advance its startup time.

**Comment by Uzaaft** [comment]
Can't you load it after UIEnter, i.e on the event: `LazyVimStarted`?

**Comment by chaozwn** [comment]
> 

After changing to LazyVimStarted, when using nvim to restore the previous page, yy becomes invalid, so we can't use this event.

**Comment by Uzaaft** [comment]
> > 
> 
> After changing to `LazyVimStarted`, when using `nvim` to restore the previous page, `yy` becomes invalid, so we can't use this event.

Got it thanks for checking that out!

**Review by Uzaaft — APPROVED** [review]

**Pull request merged**
