### PR TITLE
feat(pack): add an NvChad UI pack

### PR DESCRIPTION
**Pull request by mehalter**
## 📑 Description

Add a pack for integrating the NvChad UI toolkit in AstroNvim

### CODE REVIEW

**Comment by luxus** [comment]
wolf in sheep's clothing

**Comment by Uzaaft** [comment]
Whats blocking this  PR?

**Comment by mehalter** [comment]
@Uzaaft NvChad/ui doesn't currently actually support loading configuration like this. So it doesn't fully work. Once that gets added (if it does) then I can test this more and add the rest of the missing stuff like leybindings and whatnot

**Comment by mehalter** [comment]
@Uzaaft I opened some PRs upstream to add the missing support and now this PR works great!

**Comment by Uzaaft** [comment]
Fuck it, ship it

**Review by Uzaaft — APPROVED** [review]

**Pull request merged**
