### PR TITLE
feat(pack): enable automatic install of haskell dap

### PR DESCRIPTION
**Pull request by owittek**
Relies on https://github.com/jay-babu/mason-nvim-dap.nvim/pull/88

### CODE REVIEW

**Comment by sjcobb2022** [comment]
Oh sick nice you opened up a pull. Thanks man!

**Comment by sjcobb2022** [comment]
@owittek There are some changes that are needed to get haskell-tools to work with the haskell-debug adapter. 

My fork has the necessary changes:  https://github.com/sjcobb2022/astrocommunity

**Comment by owittek** [comment]
> @owittek There are some changes that are needed to get haskell-tools to work with the haskell-debug adapter.
> 
> My fork has the necessary changes: https://github.com/sjcobb2022/astrocommunity

You should be able to PR this to my fork so that it will be added to this PR. I don't know if there's an easier way to get those changes over here.

**Comment by sjcobb2022** [comment]
> > @owittek There are some changes that are needed to get haskell-tools to work with the haskell-debug adapter.
> > My fork has the necessary changes: https://github.com/sjcobb2022/astrocommunity
> 
> You should be able to PR this to my fork so that it will be added to this PR. I don't know if there's an easier way to get those changes over here.

I'll see what i can do.

**Comment by sjcobb2022** [comment]
@owittek pull is on ur fork.

**Comment by mehalter** [comment]
@sjcobb2022 why the Change to this line?

https://github.com/sjcobb2022/astrocommunity/blob/main/lua/astrocommunity/pack/haskell/haskell.lua#L23

**Comment by sjcobb2022** [comment]
> @sjcobb2022 why the Change to this line?
> 
> https://github.com/sjcobb2022/astrocommunity/blob/main/lua/astrocommunity/pack/haskell/haskell.lua#L23

I can change that back. Just though it looked a bit cleaner. Probably changed it when i was messing around trying to get it to work.

**Comment by mehalter** [comment]
Oh wait, @sjcobb2022 it looks like you reverted all of the new `insert_list_unique` syntax 🤔 was that accidental in resolving merge conflicts maybe?

**Comment by owittek** [comment]
> @owittek pull is on ur fork.

I have reviewed your changes. It would be the easiest to rebase your changes on top of the current master & then just add your autocmd.

**Comment by mehalter** [comment]
@owittek it might be easier for you to manually add the changes into this branch and setting @sjcobb2022 as the commit author

**Comment by sjcobb2022** [comment]
> @owittek it might be easier for you to manually add the changes into this branch and setting @sjcobb2022 as the commit author

Sorry for the hassle, it should be fixed now. I'm really crap at git.

**Comment by owittek** [comment]
@sjcobb2022 Please take a look if I have committed all your changes.

**Comment by sjcobb2022** [comment]
> @sjcobb2022 Please take a look if I have committed all your changes.

I think the dependency on [mason-nvim-dap](https://github.com/owittek/astrocommunity/blob/5e71778d6f5df674be7a478ff9405d6f19b41151/lua/astrocommunity/pack/haskell/haskell.lua#LL41C7-L41C7) should be changed.

**Comment by mehalter** [comment]
Yeah I agree, @owittek mason-nvim-dap shouldn't be in the dependency list. It should just be another item in the top level table

**Comment by sjcobb2022** [comment]
Everything looks good now!

**Comment by owittek** [comment]
> Yeah I agree, @owittek mason-nvim-dap shouldn't be in the dependency list. It should just be another item in the top level table

Don't worry, I merged the changes quicker than you can type 😜

**Comment by mehalter** [comment]
Great! Now we play the waiting game :) 

Also no worries @sjcobb2022 ! The old syntax does still work completely fine, but we did recently improve the syntax to decrease the amount of boilerplate code needed

**Comment by sjcobb2022** [comment]
mason-nvim-dap.nvim@2.1.0 has been released!

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
