### PR TITLE
feat(markdown-and-latex): install markmap from mason

### PR DESCRIPTION
**Pull request by jay-babu**

### CODE REVIEW

**Comment by mehalter** [comment]
@jay-babu does mason-null-ls super ensuring the installation of this?

**Comment by jay-babu** [comment]
> @jay-babu does mason-null-ls support ensuring the installation of this?

it is trick (or bug depending on your perspective) that I have no plans fixing :). mason-null-ls does not enforce any checks to ensure the requested tool is in `null-ls` registry

**Comment by mehalter** [comment]
Ah I see 😂 I didn't know if it would require you to use a name that would be translated to a mason name. Cool thanks! I'll merge this!

**Review by mehalter — APPROVED** [review]
LGTM!

**Comment by jay-babu** [comment]
> Ah I see 😂 I didn't know if it would require you to use a name that would be translated to a mason name. Cool thanks! I'll merge this!

Simply converts - to _ and back. Other characters are unaffected

**Pull request merged**
