### PR TITLE
fix(pack): Fix dap debugging for typescript and javascript

### LINKED ISSUE #148: error with astrocommunity.pack.typescript
I have this error with the typescript pack:

```text
Error executing luv callback:
.../.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1187: adapter.port is required for server adapter
stack traceback:
	[C]: in function 'assert'
	.../.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1187: in function <.../.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1179>
```

I already deleted ~/.cache/nvim and ~/.local/nvim and performed a very clean installation and the same error happens.

The adapter is being executed:

image

Due to this, if I try again after executing the debug the first time, it fails with another error saying there is already another process running (which makes sense...)

Any ideas what could be wrong?

### PR DESCRIPTION
**Pull request by Uzaaft**
This PR aims to finally make DAP debugging  work with TS and JS.
Should Fix #148

### CODE REVIEW

**Comment by Uzaaft** [comment]
Review? @owittek

**Comment by owittek** [comment]
image

I'm having unbound breakpoints & my DAP is not able to connect. My test project consists of a `main.ts` file with a few variable declarations & `console.log` statements.

**Comment by skriems** [comment]
you may want to take a look at #163 @Uzaaft @owittek.

That reflects my working setup using vscode-js-debug.

**Comment by Uzaaft** [comment]
Closing this PR. Let's work on  #120 together.

**Pull request closed without merging**
