### PR TITLE
fix(refactoring-nvim): improve lazy loading

### PR DESCRIPTION
**Pull request by Subjective**

### CODE REVIEW

**Review by owittek — APPROVED** [review]
LGTM!

**Comment by owittek** [comment]
Ah, almost missed it! Please edit the commit message to use the proper scope: `fix(editing-support)`

**Comment by Subjective** [comment]
Wait shouldn't it be `fix(refactoring-nvim)` as per the Review Checklist? 
> If you are modifying a pre-existing plugin or pack, the scope would be the name of the plugin folder. ex. fix(noice-nvim): fix LSP handler error

**Comment by owittek** [comment]
> Wait shouldn't it be `fix(refactoring-nvim)` as per the Review Checklist?
> 
> > If you are modifying a pre-existing plugin or pack, the scope would be the name of the plugin folder. ex. fix(noice-nvim): fix LSP handler error

Actually you're right, not sure why the pipeline failed before. And I am too sleepy to tell that it wasn't an error on your side. Sorry!

**Comment by Subjective** [comment]
Oh no, it's because I just changed the name of the PR, it was actually just `fix(refactoring)` before

**Pull request merged**
