### PR TITLE
feat(pack): add csharp support with `omnisharp`

### PR DESCRIPTION
**Pull request by ahmtsen**
## 📑 Description
This PR adds C# language support with `omnisharp` as LSP

### CODE REVIEW

**Comment by ahmtsen** [comment]
@mehalter when will this PR be merged?

**Comment by ALameLlama** [comment]
@AstroNvim/astrocommunity-maintainers This looks fine to me, it's similar to the CS pack but the LSP is different, should this be a separate pack or is there a way to can make it option and only have 1 CS pack?

**Comment by Uzaaft** [comment]
> @AstroNvim/astrocommunity-maintainers This looks fine to me, it's similar to the CS pack but the LSP is different, should this be a separate pack or is there a way to can make it option and only have 1 CS pack?

i think this is fine as is tbh

**Review by ALameLlama — APPROVED** [review]

**Comment by ALameLlama** [comment]
Ship it

**Pull request merged**
