### PR TITLE
feat(pack): added rainbow-delimiter.nvim integration for indent-blankline.nvim

### PR DESCRIPTION
**Pull request by ammuench**
## 📑 Description

Adds a plugin to create a mock of the old VSCode `bracket-pair-colorizer` based on a custom config for `indent-blankline` and `rainbow-delimiters` plus some custom color mappings & vim mappings built by myself.

Creates a "dashed" colorized line for bracket/indent pairs within AstroNvim and highlights the corresponding bracket/XMLtag to make the scope clear.

Shows the active scope based on your treesitter language pack, can be disabled/toggled by user request.  Mapping to toggle the indent highlighting in general also provided

## ℹ Additional Information

Users can turn scope highlight off with command in `README.md`.

indent-colorizer-preview

### CODE REVIEW

**Review by Uzaaft — CHANGES_REQUESTED** [review]
Please go trough your PR again

**Comment by ammuench** [comment]
> Please go trough your PR again

Apologies if I'm missing something obvious, but nothing seems to be off-spec from the contribution docs and comparing to other recent PRs?

The only thing I can see is my preview image potentially throwing the github actions parser an error possibly?  I can remove that if so, but I thought it would be valuable for a primarily visual UI update based plugin.

Otherwise my PR title seems to be meeting standards (and is passing in CI).  I don't mean to cause any additional work but I am a bit lost as to what needs fixing and would appreciate some guidance

**Comment by Uzaaft** [comment]
> > Please go trough your PR again
> 
> Apologies if I'm missing something obvious, but nothing seems to be off-spec from the contribution docs and comparing to other recent PRs?
> 
> The only thing I can see is my preview image potentially throwing the github actions parser an error possibly? I can remove that if so, but I thought it would be valuable for a primarily visual UI update based plugin.
> 
> Otherwise my PR title seems to be meeting standards (and is passing in CI). I don't mean to cause any additional work but I am a bit lost as to what needs fixing and would appreciate some guidance

You’ve got some unessecary files

**Comment by ammuench** [comment]
> > > Please go trough your PR again
> > 
> > 
> > Apologies if I'm missing something obvious, but nothing seems to be off-spec from the contribution docs and comparing to other recent PRs?
> > The only thing I can see is my preview image potentially throwing the github actions parser an error possibly? I can remove that if so, but I thought it would be valuable for a primarily visual UI update based plugin.
> > Otherwise my PR title seems to be meeting standards (and is passing in CI). I don't mean to cause any additional work but I am a bit lost as to what needs fixing and would appreciate some guidance
> 
> You’ve got some unessecary files

Removed the accidental `:q` file I accidentally touched--let me know if there's anything else i'm missing!

**Comment by Uzaaft** [comment]
I'm not sure if this better fits a recipe. 
@mehalter  Any feedback re this?

**Comment by ammuench** [comment]
> I'm not sure if this better fits a recipe. @mehalter Any feedback re this?

Happy to move it there if that makes more sense--put it with indent to match the NeovimCraft category per the contribution docs

**Comment by Uzaaft** [comment]
> Oh, also I think the location makes sense, I changed the wording a bit to match how we do the multiple copilot entries. Another approach would be to make it a "pack" since it configures multiple plugins but it makes it a bit harder to find imo. Or we could invert it to be `rainbow-delimiters-indent-blankline` and move it to the `editing-support` where the `rainbow-delimiters.nvim` entry is. I'm open to anything. The `recipes/` folder is explicitly reserved for things in the AstroNvim documentation and recipes section.

Then I think a pack makes more sense. Since it's multiple plugins being configured to work together

**Comment by mehalter** [comment]
Sounds good to me @Uzaaft ! Just updated the commit I made to move it to `pack`

**Comment by Uzaaft** [comment]
Plugin throws an error for me: 
image

**Comment by mehalter** [comment]
@Uzaaft should be fixed now

**Comment by ammuench** [comment]
> @ammuench Ok, I took a deep look at this today and have a recommendation on a different type of implementation for this that (1) greatly simplifies the implementation, (2) makes it much easier for the end user to further configure the plugins fully, (3) makes the end product a bit less distracting, and (4) adds full colorscheme support for any colorscheme that already supports `rainbow-delimiters.nvim`
> 
> Let me know what you think, I made sure this is in it's own commit so that it is quite easy to revert. This also lets us use the example image in the `indent-blankline.nvim` repo rather than including an entire image file in this repo which would be pulled on clones.

Thank you! Apologies for the delay, was tied up with work when I saw your updates.This implementation is actually something I was trying to figure out how to build with a nice default that could be overwritten by the user and was struggling.

I may take a pass at updating the defaults to match the colorscheme I built, as they were intentionally set that way for usability, but I think this overall approach makes much more sense for extendability.

I can look into hosting the image from my fork as a remote URL if that would be preferred so that it doesn't need to live in this git repo history as well.

Thank you again for the feedback and update on my code!

**Comment by mehalter** [comment]
Yeah I think the main thing is trying to make the pack usable by the masses. So integrating it in a way that supports most colorschemes is much more sensible as a default than something that supports one colorscheme. And then something specific enough for your setup should go in your user configuration

**Comment by mehalter** [comment]
I can also help you migrate your code to the override code for this pack that you can include in your user configuration. It's very simple to achieve the final product you had originally from the current code I uploaded and overriding things in your user configuration

**Comment by ammuench** [comment]
> Yeah I think the main thing is trying to make the pack usable by the masses. So integrating it in a way that supports most colorschemes is much more sensible as a default than something that supports one colorscheme. And then something specific enough for your setup should go in your user configuration

Happy to ultimately defer to this suggest--but just to make my point--my goal was recreating this old VSCode addon where the bracket-pair and scope had different effects to highlight the scope you were focused in alongside your color-coded bracket pairs, which is why I built a separate theme and character type for the highlights vs the scope ibl line.  If this is how ultimately how you'd prefer it to be, no worries, just explaining why my initial effort was so "opinionated"

**Comment by mehalter** [comment]
The shared image actually looks just like what the code I pushed does where the indentation lines are the normal dim and then the color matches the bracket pairs as such which I think looks great as a default:

2024-04-23_12:29:31_screenshot

**Comment by mehalter** [comment]
I did go ahead and add the show start and end back to my code to get that top line for example

**Comment by mehalter** [comment]
With the tighter integration with rainbow delimiters, to recreate your original code after you import this pack you can simply put this in your `plugins/` folder:

```lua
return {
  {
    "HiPhish/rainbow-delimiters.nvim",
    opts = {
      highlight = {
        "RainbowRed",
        "RainbowYellow",
        "RainbowBlue",
        "RainbowOrange",
        "RainbowGreen",
        "RainbowViolet",
        "RainbowCyan",
      },
    },
  },
  {
    "lukas-reineke/indent-blankline.nvim",
    opts = {
      scope = { char = "▏", show_start = true, show_end = true },
      indent = {
        char = "╎",
        highlight = {
          "RainbowRedIndent",
          "RainbowYellowIndent",
          "RainbowBlueIndent",
          "RainbowOrangeIndent",
          "RainbowGreenIndent",
          "RainbowVioletIndent",
          "RainbowCyanIndent",
        },
      },
    },
  },
}
```

This assumes you have correctly set up the highlight groups, you can also extend AstroUI to more safely add in those highlight groups only if they don't exist in the colorscheme that is being loaded for example:

```lua
return {
  {
    "AstroNvim/astroui",
    ---@param opts AstroUIOpts
    opts = function(_, opts)
      if not opts.highlights then opts.highlights = {} end
      local init_highlights = opts.highlights.init or {}
      opts.highlights.init = function(colorscheme)
        if type(init_highlights) == "function" then init_highlights = init_highlights(colorscheme) end
        for hlgroup, fallback in pairs {
          RainbowRed = { fg = "#E06C75" },
          RainbowYellow = { fg = "#E5C07B" },
          RainbowBlue = { fg = "#61AFEF" },
          RainbowOrange = { fg = "#D19A66" },
          RainbowGreen = { fg = "#98C379" },
          RainbowViolet = { fg = "#C678DD" },
          RainbowCyan = { fg = "#56B6C2" },
          RainbowRedIndent = { fg = "#6e171e" },
          RainbowYellowIndent = { fg = "#765517" },
          RainbowBlueIndent = { fg = "#0c497a" },
          RainbowOrangeIndent = { fg = "#603d1d" },
          RainbowGreenIndent = { fg = "#3b5727" },
          RainbowVioletIndent = { fg = "#5a1b6d" },
          RainbowCyanIndent = { fg = "#1e4c52" },
        } do
          if vim.fn.hlexists(hlgroup) ~= 1 then init_highlights[hlgroup] = fallback end
        end
        return init_highlights
      end
    end,
  },
  {
    "HiPhish/rainbow-delimiters.nvim",
    opts = {
      highlight = {
        "RainbowRed",
        "RainbowYellow",
        "RainbowBlue",
        "RainbowOrange",
        "RainbowGreen",
        "RainbowViolet",
        "RainbowCyan",
      },
    },
  },
  {
    "lukas-reineke/indent-blankline.nvim",
    opts = {
      scope = { char = "▏", show_start = true, show_end = true },
      indent = {
        char = "╎",
        highlight = {
          "RainbowRedIndent",
          "RainbowYellowIndent",
          "RainbowBlueIndent",
          "RainbowOrangeIndent",
          "RainbowGreenIndent",
          "RainbowVioletIndent",
          "RainbowCyanIndent",
        },
      },
    },
  },
}
```

This would get you what you originally shared which had those extra dashed indent lines and uses your own custom highlight groups that wouldn't necessarily be supported by any other colorscheme:


2024-04-23_12:35:34_screenshot

**Comment by mehalter** [comment]
Let me know what you think @ammuench , my main point being I think the code that I pushed perfectly emulates the original Bracket Pair Colorizer 2 addon like you are looking for. Not sure if you tried it and didn't agree

**Comment by ammuench** [comment]
> Let me know what you think @ammuench , my main point being I think the code that I pushed perfectly emulates the original Bracket Pair Colorizer 2 addon like you are looking for. Not sure if you tried it and didn't agree

This looks good to me!  Appreciate the extra time with examples, it all finally clicked.

**Review by mehalter — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
