### PR TITLE
Use yarn instead of npm for x6 installation speed.

### PR DESCRIPTION
**Pull request by Zeioth**
Using npm this plugin lags behind all the others during the installation process. Using yarn this is solved.

### CODE REVIEW

**Comment by Uzaaft** [comment]
Please change your PR text to follow the semantic commit spec.

**Comment by Uzaaft** [comment]
Also. I’m not a fan of this PR. Yarn is not included in node, but npm is. We should use the standard tool.

**Comment by Uzaaft** [comment]
Any thoughts @AstroNvim/astrocommunity-maintainers about using yarn instead of npm? It might end up failing on people’s machines.

**Comment by mehalter** [comment]
Yeah I agree that this should be `npm` for general applicability especially since that is what Mason is using already as well

**Pull request closed without merging**
