### PR TITLE
feat(vimtex): add which-key mapping descriptions

### PR DESCRIPTION
**Pull request by Subjective**
<details>
<summary>Before</summary>

image

</details>

<details>
<summary>After</summary>

image

</details>

### CODE REVIEW

**Review by Uzaaft — APPROVED** [review]
LGTM

**Comment by Uzaaft** [comment]
@Subjective  Why didn't you use the keys table in lazy.nvim to setup the keys?

**Comment by Subjective** [comment]
@Uzaaft VimTex sets up the keybinds by default upon entering a latex buffer, but doesn't add the descriptions necessary for which-key. The main reason for not using the lazy table is that I want the labels to be specific to that buffer.

**Review by mehalter — APPROVED** [review]
Cool thanks. Just be sure to track the changes on `vimtex` and come back when these mappings inevitably change 😅

**Pull request merged**
