### PR TITLE
feat(html-css): add emmet_ls to html-css supprt syntax like `li * 5`

### PR DESCRIPTION
**Pull request by chaozwn**
add emmet_ls to html-css supprt syntax like `li * 5`

### CODE REVIEW

**Review by Uzaaft — APPROVED** [review]
LGTM

**Comment by tofulm** [comment]
@chaozwn do you know : https://github.com/kozer/emmet-language-server
I tested it, and it's better than emmet-ls

**Comment by Uzaaft** [comment]
[kozer/emmet-language-server](https://github.com/kozer/emmet-language-server) seems unmaintained

**Comment by tofulm** [comment]
sorry, it's https://github.com/olrtg/emmet-language-server

**Comment by Uzaaft** [comment]
It's very new, so I think we should stay away from it for now. Perhaps we'll move to it in the future.

**Comment by chaozwn** [comment]
> sorry, it's https://github.com/olrtg/emmet-language-server

emmet_language_server can not transform `m5` to `margin: 5px`,.Their functionalities are almost identical, unless there are obvious bugs. Currently, I don't feel that this new Emmet LSP has any essential features that require switching.

**Pull request merged**
