### PR TITLE
fix(main): Add missing mode in mapping declerations

### PR DESCRIPTION
**Pull request by manuuurino**
## 📑 Description

as title of this pr

### CODE REVIEW

**Comment by manuuurino** [comment]
There are also some more ive discovered

```
lua/astrocommunity/color/twilight-nvim/init.lua
lua/astrocommunity/color/vim-highlighter/init.lua
lua/astrocommunity/editing-support/telescope-undo-nvim/init.lua
lua/astrocommunity/editing-support/ultimate-autopair-nvim/init.lua
lua/astrocommunity/file-explorer/mini-files/init.lua
lua/astrocommunity/split-and-window/edgy-nvim/init.lua
lua/astrocommunity/split-and-window/minimap-vim/init.lua
```

**Review by Uzaaft — CHANGES_REQUESTED** [review]
Can you also include all the other instances of the similar error?

**Review by mehalter — APPROVED** [review]
LGTM

**Comment by manuuurino** [comment]
sure, have thought i would need to do for each file a pr because of the guidelines

**Comment by manuuurino** [comment]
have found also another one

```
lua/astrocommunity/split-and-window/hop-nvim/init.lua
```

there are also some plugins that are using the keys option from lazy, it doesnt bring any issues, but is it wanted?

**Review by Uzaaft — APPROVED** [review]

**Pull request merged**
