### PR TITLE
feat(completion): add `copilot-cmp`

### PR DESCRIPTION
**Pull request by corintho**
## 📑 Description

Adds a new way to integrate copilot with cmp, besides the current options available. This one puts copilot within cmp, instead of setting it up in parallel with it.

### CODE REVIEW

**Review by Uzaaft — CHANGES_REQUESTED** [review]
Fix the naming of the folder to follow the convention we use. Marking this one as a draft until you fix this.

**Comment by corintho** [comment]
Hi Uzaaft, what do you mean by the naming convention for the folder? I am looking at it and I do not see how it could be any different than the one used, which also sits along with other copilot configurations

**Comment by corintho** [comment]
Thinking about it further, I think you want me to use `copilot-lua-cmp` as a plugin folder name. But that name is already taken by another configuration with `copilot` and `cmp`. Although that one focus on having `copilot` **outside** of `cmp`, but both of them working together.
Mine focus on having `copilot` show **within** `cmp` and a regular completion option

**Comment by Uzaaft** [comment]
This should be copilot-cmp.

**Review by Uzaaft — CHANGES_REQUESTED** [review]
please follow naming convention of the folders.

**Review by luxus — APPROVED** [review]
i did pretty much the same Integration just some weeks ago and disliked it, it feels very slow :( but it works

**Comment by corintho** [comment]
I like it because it is less intrusive, but now I got curious to see how other options perform compared to this one

**Review by Uzaaft — APPROVED** [review]

**Pull request merged**
