### PR TITLE
feat(ruby): add ruby_lsp to list of installed lsp servers

### PR DESCRIPTION
**Pull request by dsisnero**
## 📑 Add ruby_lsp to ruby

Add ruby_lsp for additional ruby lsp support

- [ ] Not Completed
- [x] Completed

### CODE REVIEW

**Comment by Uzaaft** [comment]
@dsisnero There is already a RUBY lsp in the pack.

**Comment by dsisnero** [comment]
there is solargraph lsp, This add "ruby_lsp" in addition to the solargraph lsp

**Comment by ALameLlama** [comment]
Solargraph is a ruby lsp https://github.com/castwide/solargraph they will both do the same job so you wouldn't want to have both running.

**Comment by Uzaaft** [comment]
This PR seems be opened in confusion as to what solargraph does. Should atleast be bumped down to a draft for now.

**Comment by dsisnero** [comment]
I know what solargraph and ruby-lsp does.  I was reading the neovim discourse and saw mentions of multiple lsp servers per buffer.  Don't know if that is possible but was hoping it was.  Would like to enable ruby-lsp for some of the capabilities and solargraph for some of the lsp capabilities

**Comment by Uzaaft** [comment]
> I know what solargraph and ruby-lsp does. I was reading the neovim discourse and saw mentions of multiple lsp servers per buffer. Don't know if that is possible but was hoping it was. Would like to enable ruby-lsp for some of the capabilities and solargraph for some of the lsp capabilities

That would be VERY smart to mention up front. 
That's something you can do in your config.

**Comment by kaka-ruto** [comment]
Ruby LSP is getting a lot better now and we should consider making it the default instead of solargraph https://railsatscale.com/2024-07-18-mastering-ruby-code-navigation-major-enhancements-in-ruby-lsp-2024/

**Comment by Uzaaft** [comment]
Does it support the same feature set as solargraph? From what I've read, it doesn't seem so.

**Comment by kaka-ruto** [comment]
[Solargraph](https://solargraph.org/guides/language-server) currently supports the following
```
Hover
Completion
Signature help
Go to definition
Document symbols
Workspace symbols
Rename symbols
Find references
Formatting
Diagnostics (linting)
```

And the [Ruby LSP](https://railsatscale.com/2024-07-18-mastering-ruby-code-navigation-major-enhancements-in-ruby-lsp-2024/#hover) features include
```
Semantic highlighting
Symbol search and code outline
Linting errors and warnings (diagnostics)
Format on save
Format on type
Debugging support
Running and debugging tests through VS Code’s UI
Go to definition for classes, modules, constants and required files
Showing documentation on hover for classes, modules and constants
Completion for classes, modules, constants and require paths
Fuzzy search classes, modules and constants anywhere in the project and its dependencies (workspace symbol)
Go-to-Definition for ActiveRecord Model Callbacks and Associations
Navigation to Routes and Views
Code Navigation in .erb Files
```

Sure, a year ago Ruby LSP did not have most of these features, but this year the team has really done a lot and currently, it has more features and would be more helpful for us Ruby folks

**Comment by Uzaaft** [comment]
At the end of the day, I honestly don't care about ruby. Feel free to re-open this PR, and remove the solargraph lsp if you'd like @dsisnero. 

But your list is misleading at best. The solargraph list is incomplete, some of the  ruby-lsp stuff is not relevant to neovim at all. But again, I dont care about ruby 🤷

**Comment by kaka-ruto** [comment]
@dsisnero do you mind reopening this PR please

**Pull request closed without merging**
