### PR TITLE
feat(main): Add type hints to all opts usage for catppuccin/nvim. Catch bug in opts usage for catppuccin

### PR DESCRIPTION
**Pull request by Uzaaft**

### CODE REVIEW

**Review by luxus — APPROVED** [review]

**Comment by luxus** [comment]
is this title still okay? feat(main) didn't passed the "Conventional Commit Title (pull_request_target)" @Uzaaft

**Comment by Uzaaft** [comment]
> is this title still okay? feat(main) didn't passed the "Conventional Commit Title (pull_request_target)" @Uzaaft

We’ve used feat(main) before. I was just waiting on mehalter coming back from his vacay. feat(catppuccin) is def wrong

**Comment by luxus** [comment]
i checked the possible options feat(colorscheme): is fine.. is this fitting enough? @Uzaaft @mehalter

**Comment by Uzaaft** [comment]
> i checked the possible options feat(colorscheme): is fine.. is this fitting enough? @Uzaaft @mehalter

Let it stay as is.

**Comment by mehalter** [comment]
well now that I think about it, this probably should have just been `docs` or something rather than feat since this doesn't change anything about the functionality and just provides documentation of the types in lua 🤷🏼

**Comment by Uzaaft** [comment]
Should we edit the commit text? @mehalter

**Comment by mehalter** [comment]
Nah 😂 not bad haha

**Pull request merged**
