### PR TITLE
feat(completion): add codeium

### PR DESCRIPTION
**Pull request by JoachimR**

### CODE REVIEW

**Review by mehalter — APPROVED** [review]
LGTM

**Review by mehalter — CHANGES_REQUESTED** [review]
Can you rename the folder to `astrocommunity/completion/codeium-vim` to fit the naming convention

**Comment by Uzaaft** [comment]
@JoachimR  Mehalter said the folder.

**Comment by JoachimR** [comment]
sorry, I hope it is fine now?

**Comment by luxus** [comment]
please rename the file to codeium-vim.lua too please

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
