### PR TITLE
feat(cpp): add support for linux/arm64

### LINKED ISSUE #994: C/C++ Language Pack on linux/arm64
### Is your feature related to a problem?

Using the C/C++ Language Pack on a linux arm64 system fails.  This is because Mason fails to download an arm64 clangd binary from github.  

### Describe the new feature

Clangd is supported on linux arm64. It can be installed from a distro package manager or installed from source.  In this case clangd should jsut be added to the servers section and omitted from the ensure_installed in the C/C++ Language Pack init script

lsp/servers.lua
```
return {
  "clangd"
 }
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joshheyse**
## 📑 Description

Conditionally ensures clangd installed or uses opts.servers for arm64 system

## ℹ Additional Information

I'm not familiar with lua / astronvim coding best practices, I'm sure the control flow could be better and interested in learning how to make it more idiomatic.

### CODE REVIEW

**Comment by mehalter** [comment]
There were some bugs, so I cleaned this up and committed it manually, thanks!

**Comment by Uzaaft** [comment]
Heads up. This possibly breaks stuff for Mac users.

**Comment by joshheyse** [comment]
Right. Good call.

We need a check for OS too, it should be is_linux_arm.

Sent from my iPhone

On May 27, 2024, at 23:51, Uzair Aftab ***@***.***> wrote:

﻿

Heads up. This possibly breaks stuff for Mac users.

**Comment by mehalter** [comment]
should be fixed in latest commit to AstroCommunity

**Comment by joshheyse** [comment]
@Uzaaft thanks for the catch! 

@mehalter thanks for the immediate action!

Sorry for submitting such a glaring issue. I even use macOS for a lot of my development in astronvim. 🤦

**Pull request closed without merging**
