### PR TITLE
feat: add python debug with arguments

### PR DESCRIPTION
**Pull request by chaozwn**
add python debug with arguments

### CODE REVIEW

**Comment by Uzaaft** [comment]
Any reason why this would be required?

**Comment by chaozwn** [comment]
> Any reason why this would be required?

with out it, when debug python. i can't add arguments.

image

**Comment by Uzaaft** [comment]
Ah got it, then it makes sense. Thanks! Next time, include info like that in the PR. :)

**Review by Uzaaft — APPROVED** [review]

**Comment by chaozwn** [comment]
> Ah got it, then it makes sense. Thanks! Next time, include info like that in the PR. :)

ok, Understood, I'll make sure to do it next time.

**Pull request merged**
