### PR TITLE
chore(pack): remove pylint

### PR DESCRIPTION
**Pull request by robsonpeixoto**
Ruff already to the pylint's job but faster.

### CODE REVIEW

**Comment by owittek** [comment]
I'll wait another day for input, otherwise I'll merge it. 👍

**Comment by luxus** [comment]
thanks for the PR.
can any other python person confirm this?

**Review by owittek — APPROVED** [review]

**Comment by luxus** [comment]
i guess its fine .. in the worst case we can revert it..

**Comment by m-rutter** [comment]
Glad this has been removed, despite it being advertised as fix it still didn't play nice with virtual environments, and ruff does its job already better and faster.

**Pull request merged**
