### PR TITLE
feat(molten-nvim): enhance molten config and add custom init function and statusline

### PR DESCRIPTION
**Pull request by tku137**
## 📑 Description

This plugin config adds a custom init function for Python venvs. When calling `<Leader>mmp`, we check if a venv is activated. If it is, we check if a jupyter kernel spec for this venv already exists and `:MoltenInit` this kernel spec. If no kernel spec is found, we prompt for a unique name, create the kernel spec and `:MoltenInit` it.

It also adds a status line indication if molten is activated and what kernel is initialized.

Last but not least, I added some more useful keymaps and altered the existing one slightly as well as give a hint in the readme about setting the `python3_host_prog` variable in AstroNVim.

### CODE REVIEW

**Comment by tku137** [comment]
Anything I can do to get a forward with this PR?

**Comment by Uzaaft** [comment]
> Anything I can do to get a forward with this PR?

One of the maintainers just need to take the time out of their day to review it.

**Comment by Uzaaft** [comment]
@AstroNvim/astrocommunity-maintainers 
Gonna ask if one if you guys have any opinions on this. I dont use jupyter notebooks.

**Comment by ALameLlama** [comment]
I don't use any of this tech so unless any other @AstroNvim/astronvim-maintainers have any input we can always do a scream test and merge it and see if anyone complains

**Comment by Uzaaft** [comment]
> I don't use any of this tech so unless any other @AstroNvim/astronvim-maintainers have any input we can always do a scream test and merge it and see if anyone complains

Lets go for it.

**Pull request merged**
