### PR TITLE
fix(pack): update typescript-all-in-one disable typescript-tools to denols

### PR DESCRIPTION
**Pull request by JamsMendez**
## 📑 Description
In the pack typescript-all-in-one disable typescript-tools and tsserver to denols. Apparently tsserver is disabled but typescript-tools keeps tsserver errors active again.

## ℹ Additional Information

Screenshot 2024-04-11 111539

### CODE REVIEW

**Comment by Uzaaft** [comment]
@JamsMendez Can you explain better what this PR does? Your original message didn't make much sense for me.

**Comment by JamsMendez** [comment]
> @JamsMendez Can you explain better what this PR does? Your original message didn't make much sense for me.

Sorry @Uzaaft, the context is the following:
add in community.lua
{ import = "astrocommunity.pack.typescript-all-in-one" }
And in the astrolsp.lua configure tsserver so that the root_dir for package.json and tsconfig.json.
But when I open a Deno project the tsserver shows the errors of "cannot find name Deno", "Cannot find module...", etc.
Although the pack disables lsp tsserver, this is caused by lsp typescript-tools. As shown in the previous image.
The PR in summary disables typescript-tools so that these error messages are not displayed and Deno is the main lsp.

**Comment by Uzaaft** [comment]
I'm going to wait until I merge this one for a time when I can test it 100%.

**Comment by aslak01** [comment]
Can confirm this is an issue, I used this solution to solve: https://github.com/pmizio/typescript-tools.nvim/issues/248

**Review by mehalter — APPROVED** [review]
Did a bit of cleanup and made the modifications user facing so they can choose to disable them! I'll go ahead and merge this and if something is broken we can have follow up PRs. Also snuck in some fixes across other stuff which isn't a huge deal haha not worth another PR

**Comment by mehalter** [comment]
Thanks for starting this @JamsMendez !

**Pull request merged**
