### PR TITLE
feat(pack): add fish pack

### PR DESCRIPTION
**Pull request by manuuurino**

### CODE REVIEW

**Comment by Uzaaft** [comment]
@manuuurino  I'd appreciate it if you take a look at other similar packs before.
Also, please add `WhoIsSethDaniel/mason-tool-installer.nvim` into the pack as well with optional support

**Review by Uzaaft — CHANGES_REQUESTED** [review]
please add WhoIsSethDaniel/mason-tool-installer.nvim into the pack

**Comment by manuuurino** [comment]
forgot to mention there is no mason package for fish and fish_indent, also tried your commit and it tells me this aswell

**Comment by Uzaaft** [comment]
> forgot to mention there is no mason package for fish and fish_indent, also tried your commit and it tells me this aswell

You should mention the dependency on fish in the readme, even if its a no-brainer that it's required

**Review by Uzaaft — APPROVED** [review]

**Pull request merged**
