### PR TITLE
feat(editing-support): add `CopilotChat.nvim`

### PR DESCRIPTION
**Pull request by ALameLlama**
## 📑 Description

Add [CopilotChat.nvim](https://github.com/CopilotC-Nvim/CopilotChat.nvim) with some keybinds

### CODE REVIEW

**Comment by Uzaaft** [comment]
@ALameLlama  In what way is the lazy loading broken?

**Comment by ALameLlama** [comment]
@Uzaaft The way i understand using cmd = {} will lazy load the plugin until one of the commands if used. currently it still getting loaded on startup and taking about 100ms for this plugin alone

**Comment by Uzaaft** [comment]
Ref this from my lazy.nvim:

**Comment by ALameLlama** [comment]
Ok, so the lazy loading is breaking when I require within astrocore, I'll need to move the requires within the functions instead of having them at the top. which honestly makes complete sense when I am getting it to load them right away lol instead of when the function is called for the keys

**Comment by ALameLlama** [comment]
We can also style this a little bit, by default it creates a vertical split, but if you already have splits, then you get it in the middle and it's a little awkward.

By default it looks like this
image

but we can make it a floating window always on the right like this.
image

**Comment by Uzaaft** [comment]
I think most of these makes sense. Some of the window stuff might me opinionated, but lets see what people say.

**Review by Uzaaft — APPROVED** [review]
:shipit:

**Pull request merged**
