### PR TITLE
fix(go): enable `gofumpt` in `gopls` by default

### PR DESCRIPTION
**Pull request by mehalter**
## 📑 Description

Enables `gofumpt` over `go fmt`

### CODE REVIEW

**Comment by mehalter** [comment]
@pgr0ss does this work for you? :)

**Comment by Uzaaft** [comment]
Looks good. Should it be documented in the readme just in case?

**Comment by mehalter** [comment]
Cool, I updated the readme. @Uzaaft can you go through the review checklist as the reviewer?

**Comment by pgr0ss** [comment]
> @pgr0ss does this work for you? :)

Yep, thanks!

**Review by Uzaaft — COMMENTED** [review]
:shipit:

**Review by Uzaaft — APPROVED** [review]
:shipit:

**Pull request merged**
