### PR TITLE
feat(colorschemes)!: adding mellow, juliana, neosolarized and removing onigiri

### PR DESCRIPTION
**Pull request by luxus**

### CODE REVIEW

**Comment by Uzaaft** [comment]
@luxus  I believe this PR will break some configs, so it should be: 
`add(colorschemes)!:`
cc @mehalter

**Comment by luxus** [comment]
Because it removes onigiri? Dunno... if someone uses it :)

**Comment by Uzaaft** [comment]
Yeah because it removes onigiri, someone might use it, we can't know. Even if it's highly likely that nobody uses it

**Comment by mehalter** [comment]
Why was onigiri removed?

**Comment by mehalter** [comment]
Can't we just avoid that breaking change and not remove it?

**Comment by Uzaaft** [comment]
> Why was onigiri removed?

It's archived by the maintainer.

**Comment by mehalter** [comment]
Ok, but it can still be installed. Doesn't seem too bad to just leave it to avoid a breaking change.

**Comment by luxus** [comment]
i will do the changes later today

**Review by mehalter — CHANGES_REQUESTED** [review]
Don't remove `onigiri` but we could put an archived notice on the `README`

**Review by mehalter — APPROVED** [review]
I went ahead and just resolved all of the issues here.

**Pull request merged**
