### PR TITLE
feat(pack): Add swift pack

### PR DESCRIPTION
**Pull request by Uzaaft**
This PR adds a WIP Swift pack

### CODE REVIEW

**Comment by Uzaaft** [comment]
```lua{
 "AstroNvim/astrocommunity",
branch = "dev_swift",
...
}```

**Comment by luxus** [comment]
swift? oh wow :D

**Comment by Uzaaft** [comment]
> swift? oh wow :D

Gotta get them all.
The experience wasnt perfect, so we might just release it as is with beta status

**Review by luxus — APPROVED** [review]
lgtm

**Pull request merged**
