### PR TITLE
feat: change olexsmir/gopher.nvim to ray-x/go.nvim

### PR DESCRIPTION
**Pull request by ypli0629**
[`ray-x/go.nvim`](https://github.com/ray-x/go.nvim) provide more powerful functions

### CODE REVIEW

**Comment by Uzaaft** [comment]
@mehalter  While I agree, doesn't the change of available commands in Neovim for Go constitute an breaking change?

**Comment by mehalter** [comment]
I think for the case of AstroCommunity the things the plugins provide should be considered outside of the scope of our API

**Comment by Uzaaft** [comment]
I'll take a look at this in a couple of hours just to make sure it works as expected. Sorry about the delay in merging @ypli0629

**Comment by luxus** [comment]
Not sure about x-rayz plugins… 
Most plugins are a bit messy 

didn’t have a go project right now to test it

**Comment by Uzaaft** [comment]
LGTM. go.nvim seems to me more used, so the change makes sense.

**Review by Uzaaft — APPROVED** [review]
LGTM

**Pull request merged**
