### PR TITLE
feat(go): Add golangcilint as default linter

### PR DESCRIPTION
**Pull request by shivanthzen**
## 📑 Description

The PR adds [golangcilint](https://github.com/golangci/golangci-lint) as the default linter for go.pack. Currently no linters as part for the pack.

### CODE REVIEW

**Comment by shivanthzen** [comment]
Thanks for the revision
LGTM.

**Review by mehalter — APPROVED** [review]

**Comment by zedeus** [comment]
For me it doesn't get updated in real-time unlike gopls which already uses e.g. staticcheck for linting. It results in both lingering and duplicated warnings for me:
After save:
image
After satisfying the check, before saving:
image

I'd like either of the following options:
- Improve the golangcilint integration to be real-time without having to edit just like the default LSP is (maybe by using null-ls instead of nvim-lint? I don't know very much about plugin landscape so maybe this is nonsensical)
- A way to easily disable golangcilint (not sure how to go about it, do I have to remove that element from the array in my configuration?)

**Comment by mehalter** [comment]
@zedeus yeah it might be better for this not to be a default is gopls already has linting. Then users can opt into it. If you open a PR to revert this then I will merge it

**Comment by zedeus** [comment]
@mehalter here you go: https://github.com/AstroNvim/astrocommunity/pull/1215

**Comment by shivanthzen** [comment]
The revert makes sense. 
Is `A way to easily disable golangci_lint (not sure how to go about it, do I have to remove that element from the array in my configuration?)` this a possbility right now in Astronvim ? Can I override pack configurations ? I only know of `override.lua` which is sort of per plugin configuration.

**Comment by mehalter** [comment]
you can add it anywhere in your `plugins/` folder. It doesn't have to go in `override.lua`

**Pull request merged**
