### PR TITLE
feat(pack)!: Split python pack into python and python-ruff

### LINKED ISSUE #592: Python pack contains both ruff and isort. Is this necessary
Since ruff includes isort functionality, is it necessary to also include the isort module in the pack?

This seems redundant.

### PR DESCRIPTION
**Pull request by Uzaaft**
Closes #592

### CODE REVIEW

**Comment by Uzaaft** [comment]
This is tentatively ready to come out of draft. @AstroNvim/astrocommunity-maintainers Wanna review?

**Review by mehalter — CHANGES_REQUESTED** [review]
Shouldn't the `python-ruff` pack just import the python pack and then add `ruff-lsp`? Wouldn't reduce lots of duplicate code

**Comment by Uzaaft** [comment]
> Shouldn't the `python-ruff` pack just import the python pack and then add `ruff-lsp`? Wouldn't reduce lots of duplicate code

I could do that :)

**Comment by m-rutter** [comment]
The primary point in splitting it is not because people don't want Ruff (though that is a faction), but because isort is made redundant by ruff and because the current config somehow messes up the formatting of imports.

**Comment by Uzaaft** [comment]
> The primary point in splitting it is not because people don't want Ruff (though that is a faction), but because isort is made redundant by ruff and because the current config somehow messes up the formatting of imports when they are both present (formatting in the wrong order potentially)

Thanks for re-iterating my point.

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
