### PR TITLE
fix(nvim-ts-rainbow2): remove hack

### PR DESCRIPTION
**Pull request by utkarshgupta137**
Recently, I've noticed that my editor slows down over time. Turns out that this hack is causing the problem. Without it, there is no more slowdown.

### CODE REVIEW

**Comment by A-Lamia** [comment]
aaaah, so this is what causes the slow down i thought i was going insane.

**Comment by mehalter** [comment]
Yeah the unfortunate thing is without this autocmd, the coloring just gets messed up over time 😂 it seems that rainbow parentheses are just never going to be stable in Neovim 🤔

**Comment by A-Lamia** [comment]
not sure if it's a good idea letting people use this, maybe put a warning on the read me to let people know ?

**Comment by utkarshgupta137** [comment]
> aaaah, so this is what causes the slow down i thought i was going insane.

Me too brother, me too. You've no idea how much time I spent debugging this 😭.

> So then is there still an issue with ranbow-ts that needs the hack ?

Yes.

> if there isn't a fix i might just disabled it.

AFAIK, `nvim-rainbow-ts` doesn't have an issue with this hack. It seems like this fork changed something recently which made this hack slow down the editor.
A better fix is to do it manually once in a while. I've [created](https://github.com/utkarshgupta137/nvim-astro/commit/446b6479c08bab487f21da6b7ae080417e224776) a custom command & a mapping & I run it every few minutes. Doing it manually seems to have better results too, since there is a delay between disable & enable.

**Comment by A-Lamia** [comment]
maybe we should do it on save ?

**Comment by utkarshgupta137** [comment]
@mehalter This issue might be plaguing unsuspecting users, can we release this on priority?

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
