### PR TITLE
feat(blink-cmp): disable cmp-git

### PR DESCRIPTION
**Pull request by windowsrefund**
Ensure cmp-git is no longer enabled.

### CODE REVIEW

**Comment by Uzaaft** [comment]
@windowsrefund Do you have a reference or a link as to why this plugin needs to be disabled?

**Comment by windowsrefund** [comment]
https://github.com/AstroNvim/astrocommunity/blob/aaaa844e45420cd7b5f11b7c399bee919513d1d5/lua/astrocommunity/completion/cmp-git/init.lua#L10

**Comment by Uzaaft** [comment]
> https://github.com/AstroNvim/astrocommunity/blob/aaaa844e45420cd7b5f11b7c399bee919513d1d5/lua/astrocommunity/completion/cmp-git/init.lua#L10

Doesnt answer the questiion. Why does it have to be disabled? doesnt it work with the plugin?

**Comment by windowsrefund** [comment]
How would it work if cmp itself is disabled?

**Comment by Uzaaft** [comment]
> How would it work if cmp itself is disabled?

This one isn’t built in.

**Comment by Uzaaft** [comment]
All the other plugins being disabled are built ins.

**Review by Uzaaft — APPROVED** [review]

**Pull request merged**
