### PR TITLE
feat(pack): make dap work in typescript using vscode-js-debug

### PR DESCRIPTION
**Pull request by skriems**
Hi!

I recently moved from my nvim setup to AstroNvim and really appreciate the work! Awesome suite! I installed the typescript pack and couldn't bring DAP to work properly, basically facing the same issues as in #148.

This PR replicates my working DAP setup with vscode-js-debug in the new _lazy_ format. I hope everything is fine, I only had an issue with the `config` field for vscode-js-debug: I used `config = true` but got an error like:

```
lua module not found for vscode-js-debug. use config func instead...
```

Didn't really know what to do with that, so I did what the msg told me to do ;)

I added an `attach to port` config which I usually use while debugging a bunch of docker containers, which expose the inspector thing on different ports. I have not tested the other configs.

Resolves: #148

### CODE REVIEW

**Comment by mehalter** [comment]
@owittek and @Uzaaft have been working on revamping the typescript stuff and have done some significant restructuring. They just got these changes merged in and this is not out of date and would need rebasing. They are also planning on getting a DAP PR together in the coming week I believe. They should comment on whether or not we should get this rebased and merged in or if we should wait on what they are doing.

**Comment by owittek** [comment]
I'll take a look at it tomorrow but from the looks of it I wouldn't rebase it in its current form since the installation of `js-debug-adapter` should be done with Mason instead of building it. The only other change to the functionality is the addition of ports which might be relevant in getting it to work.

**Comment by Uzaaft** [comment]
I think we should wait. We really do not want to be dependent on `ts-node` unless we absolutely need to.

**Comment by mehalter** [comment]
Ok I'm going to go ahead and close this @skriems . I'll be sure to ping you when the new PR is opened to get your feedback though!

**Pull request closed without merging**
