### PR TITLE
feat(nvim-lint): make autocmd events configurable

### PR DESCRIPTION
**Pull request by nicholasxjy**
## 📑 Description

make `nvim-lint` autocmd events(`"BufWritePost", "BufReadPost", "InsertLeave", "TextChanged"` now) can be configured from `opts.events`

### CODE REVIEW

**Review by Uzaaft — COMMENTED** [review]
opts.events doesnt seem to be a valid field for the options that should be passed to this plugin. Not sure if we should add it, so I defer to another maintainer. But this would open the floodgates in terms scope for astrocommunity.
Also, the current plugin spec should be updated to use astrocore.

**Comment by mehalter** [comment]
Yeah we should avoid trying to modify the `opts`. I think what this should be doing is using the AstroCore autocommand creation feature which would make it configurable to the user

**Comment by mehalter** [comment]
Okay, tested and it looks good to go! Here is how the user would configure the autocommand events:

```lua
return {
  "AstroNvim/astrocore",
  opts = function(_, opts)
    -- customize the autocommand events for nvim-lint
    opts.autocmds.auto_lint[1].event = { "BufWritePost" }
  end
}
```

**Review by mehalter — APPROVED** [review]
Thanks for this! It is a great idea to make this configurable

**Pull request merged**
