### PR TITLE
feat(codesnap-nvim): support for windows users

### PR DESCRIPTION
**Pull request by Std-Enigma**
## ℹ Additional Information

This plugin at least on the latest version doesn't support windows by any means but the "0.0.x" version does however but it's not so performant and works kinda differently 

This PR make sures that windows users get the latest working version that supports their OS

### CODE REVIEW

**Comment by ALameLlama** [comment]
This looks good to me but i think @Uzaaft was looking into an upstream change

**Comment by Std-Enigma** [comment]
i mean sure but at least for now we can hack our way to get it to work for every user until they support it in the later versions

**Comment by Std-Enigma** [comment]
> upstream change 
so you mean i should I've just pushed this changes to the same pr i made a while ago?

**Comment by Uzaaft** [comment]
> > upstream change
> > so you mean i should I've just pushed this changes to the same pr i made a while ago?

What?

**Comment by Uzaaft** [comment]
@Std-Enigma can you add a note into the readme to document this behaviour

**Review by ALameLlama — APPROVED** [review]

**Comment by ALameLlama** [comment]
Lgtm

**Pull request merged**
