### PR TITLE
feat(colorscheme): add monokai-pro

### PR DESCRIPTION
**Pull request by bernwo**
Adds the [`monokai-pro`](https://github.com/loctvl842/monokai-pro.nvim) colorscheme.

### CODE REVIEW

**Comment by bernwo** [comment]
This PR is ready for review. @luxus or anyone

**Comment by Uzaaft** [comment]
LGTM. Just a question: Why  not just use the default options for the setup? I.e just doing something like:

```lua
return {
    "loctvl842/monokai-pro.nvim", 
      opts = {}
```

**Review by mehalter — CHANGES_REQUESTED** [review]
Please use the `opts` table rather than `config` function with a `setup` call

**Review by mehalter — APPROVED** [review]
moved to the `opts` notation. LGTM

**Pull request merged**
