### PR TITLE
feat(pack): add Templ language pack

### PR DESCRIPTION
**Pull request by mehalter**
## 📑 Description

This adds a pack for the [Templ](https://templ.guide/) HTML templating language

### CODE REVIEW

**Comment by Uzaaft** [comment]
@mehalter  Doesn't templ require go? Shouldnt that be included in the pack, or mentioned in the docs.

**Comment by mehalter** [comment]
No it doesn't seem to require go

**Comment by mehalter** [comment]
I mean to run the language server on a `.templ` file and to parse the treesitter it doesn't require Go

**Comment by mehalter** [comment]
we could add it tho

**Comment by mehalter** [comment]
oh actually it very much doesn't require `gopls` or anything. So it is good as is

**Pull request merged**
