### PR TITLE
fix(hardtime-nvim): add neo-tree buffer to ignore

### PR DESCRIPTION
**Pull request by nfort**

### CODE REVIEW

**Comment by nfort** [comment]
hardtime.nvim show notification when i use move (k,j) inside tree, by default hardtime.nvim disabled in NvimTree, but not Neo-Tree. After update to AstoNvim v4 begin get this notification.

**Comment by Uzaaft** [comment]
> hardtime.nvim show notification when i use move (k,j) inside tree, by default hardtime.nvim disabled in NvimTree, but not Neo-Tree. After update to AstoNvim v4 begin get this notification.

You should upstream this change then

**Comment by Uzaaft** [comment]
This PR is unneeded. All these file types are in the hardtime default config. You should open an issue upstream.

**Comment by luxus** [comment]
@nfort as long its not merged upstream you can add it to your config

```lua
return {
  "m4xshen/hardtime.nvim",
  opts = {
    disabled_filetypes = { "qf", "netrw", "NvimTree", "lazy", "mason", "neo-tree" } 
}
```

**Comment by Uzaaft** [comment]
> @nfort as long its not merged upstream you can add it to your config
> 
> ```lua
> return {
>   "m4xshen/hardtime.nvim",
>   opts = {
>     disabled_filetypes = { "qf", "netrw", "NvimTree", "lazy", "mason", "neo-tree" } 
> }
> ```

That isnt nessecary. They have been upstreamed for a while

**Pull request closed without merging**
