### PR TITLE
feat(file-explorer): Add initial support for mini.files

### LINKED ISSUE #318: testing mini.files
hi, 
i'm testing mini.files right now, if someone wanna test it or adding it to astrocommunity, feel free.
i added a `esc` binding to close the popup additionally to the `q`

```lua
    {
      "neo-tree.nvim",
      enabled = false,
	},
    {
      "echasnovski/mini.files",
      keys = {
        {
          "<leader>e",
          function() require("mini.files").open() end,
          desc = "Explorer",
        },
      },
      dependencies = {
        "nvim-tree/nvim-web-devicons",
      },
      init = function()
        vim.api.nvim_create_autocmd("User", {
          pattern = "MiniFilesBufferCreate",
          callback = function(args)
            vim.keymap.set("n", "<ESC>", function() require("mini.files").close() end, { buffer = args.buf_id })
          end,
        })
      end,
      opts = {},
    },
```

### PR DESCRIPTION
**Pull request by Uzaaft**
Fixes #318

### CODE REVIEW

**Comment by luxus** [comment]
fixes #318

**Comment by Uzaaft** [comment]
@luxus Do you think we should make this config 1:1 with what we have in astronvim?

**Review by mehalter — APPROVED** [review]
LGTM!

**Comment by luxus** [comment]
It’s a good question, what u mean with 1:1? It looks very different anyways but a little familiarity could be good. I didn’t tweak it yet, I just copied the code from folks

**Pull request merged**
