### PR TITLE
feat(code-runner): add compiler.nvim

### PR DESCRIPTION
**Pull request by Zeioth**
More info about the project can be found here: https://github.com/Zeioth/Compiler.nvim

### CODE REVIEW

**Comment by luxus** [comment]
so its depends on overseer?

**Comment by Uzaaft** [comment]
Can you fix the way you import your repo? Other repositories doesn’t seem to need the whole git url

**Comment by Zeioth** [comment]
@luxus yes, we use it to run the calls because it fits perfectly to our need. Compiler.nvim is to overseer what friendly snippets is to luasnip, you could say.

@Uza thank you for that, missed it. I've cleaned up that, and the comments too.

**Comment by Uzaaft** [comment]
Can you fix the Invalid PR title, and we'll be ready to merge 🫡

**Comment by mehalter** [comment]
I went ahead and cleaned this up and merged it in. Thanks for the contribution @Zeioth !

**Pull request merged**
